all:
  configuration:
    drev:
      prelevements: false
      mentions_complementaire: true
      import_with_mentions_complementaire: true
      validation_odg: 'auto'
      habilitation_inao: true
      cgu: true
      etape_superficie: false
      dr_douane_required: false
      degustation: true
      specificite_lot: true
      specificites:
        bio: "bio"
        effervescent: "effervescent"
        base_mousseux: "base mousseux"
        HVE: "HVE"
        aucune: "aucune"
