all:
  configuration:
    drev:
      validation_odg: 'admin'
      pdf_unique_region: true
      logement_adresse: false
      denomination_auto: true
      denomination_biodynamie: true
      engagement_pdf: true
