all:
  configuration:
    parcellaire:
      aires:
        cotedurhone:
          name: "C么tes du Rh么ne"
          color: "#b6166b"
          denumination_id: "01344"
        cdrvillage:
          name: "C么tes du Rh么ne Villages"
          color: "#52e536"
          denumination_id: "01345"
