# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  document_validation_signataire: 1
  parcellaire_irrigable:
    ressources: ["Canal de Provence", "Forage", "Etang", "Retenue collinaire","Réseau urbain"]
    materiels: ["Goutte à goutte", "Canon", "Système enterré"]
  float:
    default_decimal_format: 2
    max_decimal_authorized: 4
  societe:
    format_identifiant: "CDP%05d"
  donnees_viticoles:
    regions:
      ALPES_MARITIMES: "ALPES MARITIMES"
      ARGENS_BESSILLON: "ARGENS BESSILLON"
      BASSIN_DU_BEAUSSET: "BASSIN DU BEAUSSET" 
      DRACENIE: "DRACENIE"
      FREJUS: "FREJUS"
      GOLF_DE_ST_TROPEZ: "GOLF DE ST TROPEZ"
      LA_LONDE: "LA LONDE"
      MAURES_INTERIEURS: "MAURES INTERIEURS"
      NOTRE_DAME_DES_ANGES: "NOTRE DAME DES ANGES"
      PIERREFEU: "PIERREFEU"
      PLATEAU_KARSTIQUE: "PLATEAU KARSTIQUE"
      SAINTE_VICTOIRE: "SAINTE VICTOIRE"