all:
  configuration:
    habilitation:
      activites:
        PRODUCTEUR: "Producteur de raisins"
        PRODUCTEUR_MOUTS: "Producteur de moût"
        VINIFICATEUR: "Vinificateur"
        ELEVEUR_DGC: "Éleveur de DGC"
        VRAC: "Détenteur de vin en vrac"
        CONDITIONNEUR: "Conditionneur"
