all:
  configuration:
    habilitation:
      activites:
        'PRODUCTEUR' : "Producteur de raisins"
        'PRODUCTEUR_MOUTS' : 'Producteur de moût'
        'CONDITIONNEUR' : 'Conditionneur'
        'ELEVEUR_DGC' : 'Eleveur de DGC'
        'VINIFICATEUR' : 'Vinificateur'
        'VRAC' : 'Détenteur de vin en vrac'
