all:
  configuration:
    parcellaire:
      ecart_rangs_max: 25000
      ecart_pieds_min:  8000
      aires:
        communes-aoc:
          name: "AOC Côte de Provence"
          color: "#e58ebc"
          denomination_id: "01382"
        communes-stevictoire:
          name: "AOC Sainte-Victoire"
          color: "#52e536"
          denomination_id: "01702"
