all:
  configuration:
    parcellaire:
      ecart_rangs_max: 250
      ecart_pieds_min:  80
      aires:
        communes-aoc:
          name: "AOC Côte de Provence"
          color: "#e58ebc"
          denomination_id: "01382"
        communes-stevictoire:
          name: "AOC Sainte-Victoire"
          color: "#52e536"
          denomination_id: "01702"
        communes-cap:
          name: "AOC Coteaux d'Aix en provence"
          color: "#fcd9c7"
          denomination_id: "01380"
        communes-cvp:
          name: "AOC Coteaux Varois en provence"
          color: "#efc868"
          denomination_id: "01707"
