# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  routing_context_production_host: gascogne.igp.vins.24eme.fr
  organisme:
    nom: "Syndicat des vins Côtes de Gascogne et Gers"
  float:
    default_decimal_format: 2
    max_decimal_authorized: 4
  societe:
    format_identifiant: "GSC%06d"
  donnees_viticoles:
    regions:
      IGPGASCOGNE: "IGPGASCOGNE"
  etiquettes: "70x36" #Impression en taille rélle