all:
  configuration:
    facture:
      aggregateMouvements: false
      ligneMsg: false
      echeances: false
      all_etablissements: false
      export_sage_width_txt: true
      all_etablissements: true
      modalite_paiement: "- comptant par virement ou chèque \\ - prélèvement sous 15 jours \\"
      uniq_template_prefix: "TEMPLATE-FACTURE"
      paiements: true
