# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  routing_context_production_host: alpes.igp.vins.24eme.fr
  organisme:
    nom: "Syndicat des vins IGP des Alpes du Sud"
  float:
    default_decimal_format: 2
    max_decimal_authorized: 4
  societe:
    format_identifiant: "ALP%06d"
  donnees_viticoles:
    regions:
      IGPALPES: "IGPALPES"
