# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  organisme:
    nom: "Centre Loire"
  elasticversion: '2.4.6'
  float:
    default_decimal_format: 2
    max_decimal_authorized: 4
  societe:
    format_identifiant: "%06d"
  donnees_viticoles:
    lot_saisie_mention_cepage_active: false
    secteurs:
      AMIGNY: "AMIGNY"
      BOURG_QUINCY: "BOURG_QUINCY"
      BUE: "BUE"
      CHAVIGNOL: "CHAVIGNOL"
      COTEAUX_DU_GIENNOIS: "COTEAUX_DU_GIENNOIS"
      CREZANCY: "CREZANCY"
      EXTERIEUR: "EXTERIEUR"
      GIENNOIS: "GIENNOIS"
      ISOLES_SANCERRE: "ISOLES_SANCERRE"
      LE_BOUCHOT: "LE_BOUCHOT"
      LES_BERTHIERS: "LES_BERTHIERS"
      LES_LOGES: "LES_LOGES"
      MAIMBRAY: "MAIMBRAY"
      MAISON_BLANCHE: "MAISON_BLANCHE"
      MENETOU_RATEL: "MENETOU_RATEL"
      MENETOU_SALON: "MENETOU_SALON"
      MENETREOL: "MENETREOL"
      MONTIGNY: "MONTIGNY"
      NORD_AOC: "NORD_AOC"
      POUILLY: "POUILLY"
      QUINCY: "QUINCY"
      REUILLY: "REUILLY"
      REUILLY_CHAIS: "REUILLY_CHAIS"
      REUILLY_EST: "REUILLY_EST"
      REUILLY_OUEST: "REUILLY_OUEST"
      REUILLY_SUD: "REUILLY_SUD"
      SAINT_ANDELAIN: "SAINT_ANDELAIN"
      SANCERRE: "SANCERRE"
      SOUMARD: "SOUMARD"
      STE_GEMME: "STE_GEMME"
      ST_SATUR: "ST_SATUR"
      SURY_EN_VAUX: "SURY_EN_VAUX"
      THAUVENAY_VIGON: "THAUVENAY_VIGON"
      TRACY: "TRACY"
      VEAUGUES: "VEAUGUES"
      VERDIGNY: "VERDIGNY"
      ZONE_CENTRE: "ZONE_CENTRE"
  communes:
    denominations:
