# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  organisme:
    nom: "Centre"
  elasticversion: '2.4.6'
  document_validation_signataire: 1
  float:
    default_decimal_format: 2
    max_decimal_authorized: 4
  societe:
    format_identifiant: "%06d"
  donnees_viticoles:
    regions:
      SECTEUR_1: "Secteur 1"
      SECTEUR_2: "Secteur 2"
      SECTEUR_3: "Secteur 3"
      SECTEUR_4: "Secteur 4"
  communes:
    denominations:
