all:
  configuration:
    degustation:
      anonymisation_manuelle: true
      avis:
        favorable: "Fav."
        defavorable: "Def."
      conformite:
        - CONFORME
        - NONCONFORME_ANALYTIQUE
        - NONCONFORME_ORGANOLEPTIQUE
