all:
  configuration:
    degustation:
      nb_etiquettes: 4
      anonymisation_manuelle: true
      conformite:
        - CONFORME
        - NONCONFORME_ANALYTIQUE
        - NONCONFORME_ORGANOLEPTIQUE
