all:
  configuration:
    habilitation:
      activites:
        PRODUCTEUR: "Producteur de raisins"
        VINIFICATEUR: "Vinificateur"
        CONDITIONNEUR: "Conditionneur"
        PRODUCTEUR_MOUTS: "Producteur de moût"
        PRESSURAGE: "Pressurage"
        ELEVEUR: "Éleveur"
        NEGOCIANT: "Négociant"
