all:
  configuration:
    parcellaire:
      ecart_pieds_max: 25000
      manquant:
        mandatory: true
      aires:
        communes-aoc:
          name: "AOC Centre"
          color: "#e58ebc"
          denomination_id: "01382"