all:
  configuration:
    facture:
      aggregateMouvements: false
      ligneMsg: false
      echeances: false
      all_etablissements: false
      uniq_template_prefix: false
      export_sage_width_txt: true
      all_etablissements: true
      numero_campagne: true
      numero_format: "%02d%05d"
