all:
  configuration:
    facture:
      ligneUnique: false
      ligneDetailWithTitle: true
      echeances: false
      uniq_template_prefix: false
      export_sage_width_txt: true
      numero_campagne: true
      numero_format: "%02d%05d"
      modalite_paiement: "Modalités de paiements : \\ - Comptant par virement ou chèque libellé à l’ordre de Fédération des Vins de Nantes \\ - Prélèvement automatique ou virement maximum en 10 fois de février à novembre"
      uniq_template_prefix: "TEMPLATE-FACTURE-AOC"
      paiements: true
