all:
  configuration:
    habilitation:
      activites:
         PRODUCTEUR: "Producteur de raisin"
         VINIFICATEUR: "Vinificateur"
         VRAC: "Détenteur de vin en vrac"
         CONDITIONNEUR: "Conditionneur"
         ELABORATEUR: "Élaborateur"
         VENTE_A_LA_TIREUSE: "Vente tireuse"
         PRODUCTEUR_MOUTS: "Producteur de moût"
         ELEVEUR_DGC: "Éleveur de DGC"
