all:
  configuration:
    habilitation:
      activites:
         PRODUCTEUR: "Producteur"
         VINIFICATEUR: "Vinificateur"
         VRAC: "Vrac"
         CONDITIONNEUR: "Conditionneur"
         ELABORATEUR: "Élaborateur"
         VENTE_A_LA_TIREUSE: "Vente tireuse"
