all:
  configuration:
    facture:
      ligneUnique: false
      ligneDetailWithTitle: false
      echeances: false
      all_etablissements: false
      uniq_template_prefix: false
      export_sage_width_txt: true
      numero_format: "%02d%05d"
      delais_paiement: "+30 days"
      uniq_template_prefix: "TEMPLATE-FACTURE-AOC"
