all:
  configuration:
    parcellaire:
      limit_produits_configuration: false
      unit: "ares"
      aires:
        CremantAlsace:
          name: "Crémant d’Alsace"
          color: "#ffffff"
          denomination_id: "00003"
        Alsace:
          name: "Alsace"
          color: "#ffeb62"
          denomination_id: "00001"
        Communale00002:  
          name: "Alsace Klevener de Heiligenstein"
          color: "#f48e00"
          denomination_id: "00002"
        Communale02450:  
          name: "Alsace Blienschwiller"
          color: "#f48e00"
          denomination_id: "02450"
        Communale02454:  
          name: "Alsace Côtes de Barr"
          color: "#f48e00"
          denomination_id: "02454"
        Communale02456:  
          name: "Alsace Côte de Rouffach"
          color: "#f48e00"
          denomination_id: "02456"
        Communale02459:  
          name: "Alsace Ottrott"
          color: "#f48e00"
          denomination_id: "02459"
        Communale02460:  
          name: "Alsace Rodern"
          color: "#f48e00"
          denomination_id: "02460"
        Communale02461:  
          name: "Alsace Saint-Hippolyte"
          color: "#f48e00"
          denomination_id: "02461"
        Communale02462:  
          name: "Alsace Scherwiller"
          color: "#f48e00"
          denomination_id: "02462"
        Communale02482:  
          name: "Alsace Vallée Noble"
          color: "#f48e00"
          denomination_id: "02482"
        Communale02484:  
          name: "Alsace Val Saint Grégoire"
          color: "#f48e00"
          denomination_id: "02484"
        Communale02485:  
          name: "Alsace Wolxheim"
          color: "#f48e00"
          denomination_id: "02485"
        Communale02842:  
          name: "Alsace Bergheim"
          color: "#f48e00"
          denomination_id: "02842"
        Communale02843:  
          name: "Alsace Coteaux du Haut Koenigsbourg"
          color: "#f48e00"
          denomination_id: "02843"  
        GrandCru00004:
          name: "Alsace grand cru Altenberg de Bergbieten"
          color: "#d10500"
          denomination_id: "00004"
        GrandCru00005:
          name: "Alsace grand cru Altenberg de Bergheim"
          color: "#d10500"
          denomination_id: "00005"
        GrandCru00006:
          name: "Alsace grand cru Altenberg de Wolxheim"
          color: "#d10500"
          denomination_id: "00006"
        GrandCru00007:
          name: "Alsace grand cru Brand"
          color: "#d10500"
          denomination_id: "00007"
        GrandCru00008:
          name: "Alsace grand cru Bruderthal"
          color: "#d10500"
          denomination_id: "00008"
        GrandCru00009:
          name: "Alsace grand cru Eichberg"
          color: "#d10500"
          denomination_id: "00009"
        GrandCru00010:
          name: "Alsace grand cru Engelberg"
          color: "#d10500"
          denomination_id: "00010"
        GrandCru00011:
          name: "Alsace grand cru Florimont"
          color: "#d10500"
          denomination_id: "00011"
        GrandCru00012:
          name: "Alsace grand cru Frankstein"
          color: "#d10500"
          denomination_id: "00012"
        GrandCru00013:
          name: "Alsace grand cru Froehn"
          color: "#d10500"
          denomination_id: "00013"
        GrandCru00014:
          name: "Alsace grand cru Furstentum"
          color: "#d10500"
          denomination_id: "00014"
        GrandCru00015:
          name: "Alsace grand cru Geisberg"
          color: "#d10500"
          denomination_id: "00015"
        GrandCru00016:
          name: "Alsace grand cru Gloeckelberg"
          color: "#d10500"
          denomination_id: "00016"
        GrandCru00017:
          name: "Alsace grand cru Goldert"
          color: "#d10500"
          denomination_id: "00017"
        GrandCru00018:
          name: "Alsace grand cru Hatschbourg"
          color: "#d10500"
          denomination_id: "00018"
        GrandCru00019:
          name: "Alsace grand cru Hengst"
          color: "#d10500"
          denomination_id: "00019"
        GrandCru00020:
          name: "Alsace grand cru Kanzlerberg"
          color: "#d10500"
          denomination_id: "00020"
        GrandCru00022:
          name: "Alsace grand cru Kessler"
          color: "#d10500"
          denomination_id: "00022"
        GrandCru00023:
          name: "Alsace grand cru Kirchberg de Barr"
          color: "#d10500"
          denomination_id: "00023"
        GrandCru00024:
          name: "Alsace grand cru Kirchberg de Ribeauvillé"
          color: "#d10500"
          denomination_id: "00024"
        GrandCru00025:
          name: "Alsace grand cru Kitterlé"
          color: "#d10500"
          denomination_id: "00025"
        GrandCru00026:
          name: "Alsace grand cru Mambourg"
          color: "#d10500"
          denomination_id: "00026"
        GrandCru00027:
          name: "Alsace grand cru Mandelberg"
          color: "#d10500"
          denomination_id: "00027"
        GrandCru00028:
          name: "Alsace grand cru Marckrain"
          color: "#d10500"
          denomination_id: "00028"
        GrandCru00029:
          name: "Alsace grand cru Moenchberg"
          color: "#d10500"
          denomination_id: "00029"
        GrandCru00030:
          name: "Alsace grand cru Muenchberg"
          color: "#d10500"
          denomination_id: "00030"
        GrandCru00031:
          name: "Alsace grand cru Ollwiller"
          color: "#d10500"
          denomination_id: "00031"
        GrandCru00032:
          name: "Alsace grand cru Osterberg"
          color: "#d10500"
          denomination_id: "00032"
        GrandCru00033:
          name: "Alsace grand cru Pfersigberg"
          color: "#d10500"
          denomination_id: "00033"
        GrandCru00034:
          name: "Alsace grand cru Pfingstberg"
          color: "#d10500"
          denomination_id: "00034"
        GrandCru00035:
          name: "Alsace grand cru Praelatenberg"
          color: "#d10500"
          denomination_id: "00035"
        GrandCru00036:
          name: "Alsace grand cru Rangen"
          color: "#d10500"
          denomination_id: "00036"
        GrandCru00037:
          name: "Alsace grand cru Rosacker"
          color: "#d10500"
          denomination_id: "00037"
        GrandCru00038:
          name: "Alsace grand cru Saering"
          color: "#d10500"
          denomination_id: "00038"
        GrandCru00039:
          name: "Alsace grand cru Schlossberg"
          color: "#d10500"
          denomination_id: "00039"
        GrandCru00040:
          name: "Alsace grand cru Schoenenbourg"
          color: "#d10500"
          denomination_id: "00040"
        GrandCru00041:
          name: "Alsace grand cru Sommerberg"
          color: "#d10500"
          denomination_id: "00041"
        GrandCru00042:
          name: "Alsace grand cru Sonnenglanz"
          color: "#d10500"
          denomination_id: "00042"
        GrandCru00043:
          name: "Alsace grand cru Spiegel"
          color: "#d10500"
          denomination_id: "00043"
        GrandCru00044:
          name: "Alsace grand cru Sporen"
          color: "#d10500"
          denomination_id: "00044"
        GrandCru00045:
          name: "Alsace grand cru Steinert"
          color: "#d10500"
          denomination_id: "00045"
        GrandCru00046:
          name: "Alsace grand cru Steingrubler"
          color: "#d10500"
          denomination_id: "00046"
        GrandCru00047:
          name: "Alsace grand cru Steinklotz"
          color: "#d10500"
          denomination_id: "00047"
        GrandCru00048:
          name: "Alsace grand cru Vorbourg"
          color: "#d10500"
          denomination_id: "00048"
        GrandCru00049:
          name: "Alsace grand cru Wiebelsberg"
          color: "#d10500"
          denomination_id: "00049"
        GrandCru00050:
          name: "Alsace grand cru Wineck-Schlossberg"
          color: "#d10500"
          denomination_id: "00050"
        GrandCru00051:
          name: "Alsace grand cru Winzenberg"
          color: "#d10500"
          denomination_id: "00051"
        GrandCru00052:
          name: "Alsace grand cru Zinnkoepfle"
          color: "#d10500"
          denomination_id: "00052"
        GrandCru00053:
          name: "Alsace grand cru Zotzenberg"
          color: "#d10500"
          denomination_id: "00053"
        GrandCru01765:
          name: "Alsace grand cru Kaefferkopf"
          color: "#d10500"
          denomination_id: "01765"