all:
  configuration:
    facture:
      ligneUnique: false
      ligneDetailWithTitle: false
      echeances: false
      all_etablissements: false
      uniq_template_prefix: false
      export_sage_width_txt: false
