all:
  configuration:
    drev:
      prelevements: false
      mentions_complementaire: true
      import_with_mentions_complementaire: true
      validation_odg: true
      habilitation_inao: true
      odg:
        ANJOU_SAUMUR:
          produits:
            - "appellations/ANJ"
            - "appellations/ANJCDL"
            - "appellations/AJV"
            - "appellations/AJVBRI"
            - "appellations/CAJ"
            - "appellations/CLO"
            - "appellations/CAS"
            - "appellations/COS"
            - "appellations/RAJ"
            - "appellations/SAU"
            - "appellations/SAUCHA"
            - "appellations/SAU"
          inao: "data/drev/FEDE.csv"
        CHINON:
          produits:
            - "appellations/CHI"
        NANTES:
          produits:
            - appellations/MUSAC
            - appellations/MUSCDL
            - appellations/MUSCGL
            - appellations/MUSSM
            - appellations/GPL
          inao: "data/drev/NANTES.csv"
        IGP_VALDELOIRE:
          produits:
            - certifications/IGP_VALDELOIRE/genres/TRANQ/appellations/VAL
