all:
  configuration:
    drev:
      prelevements: false
      mentions_complementaire: true
      import_with_mentions_complementaire: true
      validation_odg: true
      habilitation_inao: true
      odg:
        ANJOU_SAUMUR:
          nom: "Anjou Saumur"
          adresse: "73 rue du Plantagenêt, 49024 Angers"
          produits:
            - "appellations/ANJ"
            - "appellations/ANJCDL"
            - "appellations/AJV"
            - "appellations/AJVBRI"
            - "appellations/BON"
            - "appellations/CAJ"
            - "appellations/CLO"
            - "appellations/CAS"
            - "appellations/COL"
            - "appellations/COS"
            - "appellations/RAJ"
            - "appellations/SAU"
            - "appellations/SAUCHA"
            - "appellations/SAU"
            - "appellations/RLO"
          inao: "data/drev/FEDE.csv"
        TOURAINE:
          nom: "Touraine"
          adresse: "ZI 4 rue Gutenberg, 41140 NOYERS SUR CHER"
          produits:
            - "appellations/TOU"
          inao: "data/drev/FEDE.csv"
        CHINON:
          nom: "Syndicat des Vins de Chinon"
          adresse: "place Hofheim, 37500 Chinon"
          produits:
            - "appellations/CHI"
        NANTES:
          nom: "La Fédération des vins de Nantes"
          adresse: "Château de la Frémoire, 44120 Vertou"
          produits:
            - appellations/MUSAC
            - appellations/MUSCDL
            - appellations/MUSCGL
            - appellations/MUSSM
            - appellations/GPL
          inao: "data/drev/NANTES.csv"
        COTEAUX_VENDOMOIS:
          nom: "Côteaux du vendomois"
          produits:
            - appellations/CTXV
        IGP_VALDELOIRE:
          nom: "Syndicat des Vins IGP du Val de Loire"
          adresse: "37 avenue jean Joxé, 49100 Angers"
          email: "contact@vinsvaldeloire.pro"
          email_notification: "contact@vinsvaldeloire.pro"
          produits:
            - certifications/IGP_VALDELOIRE/genres/TRANQ/appellations/VAL
        SAINT_NICOLAS:
          nom: "Syndicat des Vins de Saint Nicolas de Bourgueil"
          adresse: "33 avenue Saint-Vincent 37140 Saint Nicolas de Bourgueil"
          produits:
            - TRANQ/appellations/STN
