all:
  configuration:
    drev:
      prelevements: false
      mentions_complementaire: true
      import_with_mentions_complementaire: true
      validation_odg: true
      habilitation_inao: true
      odg:
        ANJOU_SAUMUR:
          nom: "Anjou Saumur"
          adresse: "73 rue du Plantagenêt, 49024 Angers"
          produits:
            - "TRANQ/appellations/ANJ"
            - "TRANQ/appellations/ANJCDL"
            - "TRANQ/appellations/AJV"
            - "EFF/appellations/ANJ"
            - "appellations/AJVBRI/"
            - "appellations/BON/"
            - "TRANQ/appellations/CAJ/"
            - "EFF/appellations/CLO/"
            - "appellations/COL/mentions/DEFAUT"
            - "appellations/COL/mentions/SGN"
            - "appellations/COS/"
            - "appellations/COB/"
            - "appellations/RAJ/"
            - "EFF/appellations/SAU/"
            - "TRANQ/appellations/SAU/"
            - "TRANQ/appellations/SAUCHA/"
            - "appellations/RLO/"
            - "appellations/QDC/"
            - "appellations/SAV/"
            - "appellations/SAVRAM/"
            - "appellations/SAVCDS/"
          inao: "data/drev/FEDE.csv"
        TOURAINE:
          nom: "Touraine"
          adresse: "ZI 4 rue Gutenberg, 41140 NOYERS SUR CHER"
          produits:
            - "TRANQ/appellations/TOU/"
            - "TRANQ/appellations/TOUNJO/"
            - "EFF/appellations/TOU"
          inao: "data/drev/FEDE.csv"
        CHINON:
          nom: "Syndicat des Vins de Chinon"
          adresse: "place Hofheim, 37500 Chinon"
          produits:
            - "TRANQ/appellations/CHI/"
        NANTES:
          nom: "La Fédération des vins de Nantes"
          adresse: "Château de la Frémoire, 44120 Vertou"
          produits:
            - TRANQ/appellations/MUSAC
            - TRANQ/appellations/MUSCDL
            - TRANQ/appellations/MUSCGL
            - TRANQ/appellations/MUSSM
            - TRANQ/appellations/GPL
            - TRANQ/appellations/COA
          inao: "data/drev/NANTES.csv"
        COTEAUX_VENDOMOIS:
          nom: "Côteaux du vendomois"
          produits:
            - appellations/CTXV
        IGP_VALDELOIRE:
          nom: "Syndicat des Vins IGP du Val de Loire"
          adresse: "37 avenue jean Joxé, 49100 Angers"
          email: "contact@vinsvaldeloire.pro"
          email_notification: "contact@vinsvaldeloire.pro"
          produits:
            - certifications/IGP_VALDELOIRE/genres/TRANQ/appellations/VAL
        SAINT_NICOLAS:
          nom: "Syndicat des Vins de Saint Nicolas de Bourgueil"
          adresse: "33 avenue Saint-Vincent 37140 Saint Nicolas de Bourgueil"
          produits:
            - TRANQ/appellations/STN
        HAUT_POITOU:
          nom: "Syndicat des Vins du Haut Poitou"
          adresse: "Téléport 4 - Avenue Thomas Edison, Asterama 1, 86360 Chasseneuil-du-Poitou"
          produits:
            - TRANQ/appellations/HPT
          inao: "data/drev/HAUT_POITOU.csv"
