all:
  configuration:
    drev:
      prelevements: false
      mentions_complementaire: true
      import_with_mentions_complementaire: true
      validation_odg: true
      habilitation_inao: true
      odg:
        ANJOU_SAUMUR:
          nom: "Anjou Saumur"
          adresse: "73 rue du Plantagenêt, 49024 Angers"
          produits:
            - "appellations/ANJ"
            - "appellations/ANJCDL"
            - "appellations/AJV"
            - "appellations/AJVBRI"
            - "appellations/CAJ"
            - "appellations/CLO"
            - "appellations/CAS"
            - "appellations/COS"
            - "appellations/RAJ"
            - "appellations/SAU"
            - "appellations/SAUCHA"
            - "appellations/SAU"
          inao: "data/drev/FEDE.csv"
        CHINON:
          nom: "Syndicat des Vins de Chinon"
          adresse: "place Hofheim, 37500 Chinon"
          produits:
            - "appellations/CHI"
        NANTES:
          nom: "La Fédération des vins de Nantes"
          adresse: "Château de la Frémoire, 44120 Vertou"
          produits:
            - appellations/MUSAC
            - appellations/MUSCDL
            - appellations/MUSCGL
            - appellations/MUSSM
            - appellations/GPL
          inao: "data/drev/NANTES.csv"
        IGP_VALDELOIRE:
          nom: "Syndicat des Vins IGP du Val de Loire"
          adresse: "37 avenue jean Joxé, 49100 Angers"
          produits:
            - certifications/IGP_VALDELOIRE/genres/TRANQ/appellations/VAL
