all:
  configuration:
    facture:
      ligneUnique: false
      ligneDetailWithTitle: false
      echeances: false
      all_etablissements: false
      export_sage_width_txt: true
      all_etablissements: true
      modalite_paiement: "- comptant par virement ou chèques"
      uniq_template_prefix: "TEMPLATE-FACTURE"
      paiements: true
      export_type: "sage"
      codejournal_facture: 'VE'
      codejournal_paiement: 'CRCA2'
      comptetva_normal: '44571001'
      comptetva_superreduit: ''
      numerocompte_banquepaiement: '51200001'
