creation:
  is_secure: false

creationConfirmation:
  is_secure: false

motDePasseOublie:
  is_secure: false
  
creationAdmin:
  is_secure: false
  
visualisationAdmin:
  is_secure: false
  
modificationAdmin:
  is_secure: false
  
recherche:
  is_secure: false
