all:
  configuration:
    drev:
      validation_odg: 'region'
      pdf_unique_region: true
      logement_adresse: false
      logement_chais: true
      denomination_auto: true
      engagement_pdf: true
