# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
#all:
all:
  routing_context_production_host: declaration.ava-aoc.fr
  auth_mode: NO_CAS #NO_CAS, CAS
  cas:
    domain: login.vinsalsace.pro
    port: 443
    path: cas
    url: "https://login.vinsalsace.pro/cas"
  ac_exception_notifier:
    enabled: true
    email:
      from: "declaration@ava-aoc.fr"
      from_name: "acExceptionNotifierPlugin"
      to: ["vins@actualys.com"]
      subject: "[AVA Prod] Erreur 500 : %title%"
  email_plugin:
    from_adresse: declaration@ava-aoc.fr
    from_name: "Webmaster ava-aoc.fr"
    reply_to_adresse: "m.parisot@ava-aoc.fr"
    reply_to_name: "Martine Parisot"
    to_notification: ["vicky@ava-aoc.fr", "m.parisot@ava-aoc.fr", "v.wetta@ava-aoc.fr"]
  url:
    civa: "https://declaration.vinsalsace.pro"
    compte_mot_de_passe: "https://declaration.vinsalsace.pro/mon_compte"
    compte_creation: "https://declaration.vinsalsace.pro/compte"
    compte_mot_de_passe_oublie: "https://declaration.vinsalsace.pro/mot_de_passe_oublie"
    dr_recuperation: "https://declaration.vinsalsace.pro/declaration/transmission"
  dates_ouverture:
    drev: 
      debut: "2016-10-24"
      fin: "2018-06-21"
    drevmarc:
      debut: "2016-10-24"
      fin: "2017-09-01"
    parcellaire:
      debut: "2017-02-01"
      fin: "2017-06-01"
    parcellaire_cremant:
      debut: "2017-02-01"
      fin: "2017-10-01"
    tirage:
      debut: "2015-11-15"
      fin: "2018-05-31"
  osm:
    url_search: "http://www.ideeslibres.org/Bano/q2.php"
    return_format: "json"
  degustation_courrier:
    responsable: "Vicky Chan Fook Tin"
    visitetel: "03.89.20.16.58"
    visiteorga: "Martine Parisot"
    adresse:
      raison_sociale: "AVA - Organisme de Défense et de Gestion des Appellations"
      adresse: "Maison des Vins d'Alsace - 12, Avenue de la Foire aux Vins"
      cp_ville: "B.P. 91225 - 68012 COLMAR Cedex"
      telephone: "Téléphone 03 89 20 16 50 - Fax 03 89 20 16 60"
      email: "Email : info@ava-aoc.fr"
  facture:
    emetteur:
      ALSACE:
        adresse: "12 avenue de la Foire aux Vins - B.P. 91225"
        code_postal: "68012"
        ville: "COLMAR Cedex"
        service_facturation: "Maison des Vins d'Alsace"
        telephone: "Téléphone 03 89 20 16 50 - Télécopie 03 89 20 16 60"
        email: "info@ava-aoc.fr"
  contenances:
    bouteilles:
      "75 cl": 75
      "37,5 cl": 37.5
      "150 cl": 150
      "300 cl": 300