# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules

auth_login:
  url: /login
  param: { module: auth, action: login }

auth_logout:
  url: /logout
  param: { module: auth, action: logout }

home:
  url: /
  param: { module: ava, action: home }

contact:
  url: /contact
  param: { module: ava, action: contact }

mentions_legales:
  url: /mentions-legales
  param: { module: ava, action: mentionsLegales }

admin:
  url: /admin
  param: { module: admin, action: index }

admin_doc:
  url: /admin/doc
  param: { module: admin, action: doc }

drev_index:
  url: /drev
  param: { module: drev, action: index }

drev_request_dr:
  url: /drev/dr/request
  param: { module: drev, action: requestDR }

drev_push_dr:
  url: /drev/dr/push
  param: { module: drev, action: pushDR }

drev_pull_dr:
  url: /drev/dr/pull
  param: { module: drev, action: pullDR }

drev_create:
  url: /drev/creation/:id
  param: { module: drev, action: create }
  class: EtablissementRoute
  options:
    model:    Etablissement
    type:     object
  requirements:
    sf_method: [get]

drev_create_papier:
  url: /drev/creation-papier/:id
  param: { module: drev, action: createPapier }
  class: EtablissementRoute
  options:
    model:    Etablissement
    type:     object
  requirements:
    sf_method: [get]

drev_edit:
  url: /drev/edition/:id
  param: { module: drev, action: edit }
  class: DRevRoute
  options:
    model:    DRev
    type:     object
  requirements:
    sf_method: [get]

drev_delete:
  url: /drev/suppression/:id
  param: { module: drev, action: delete }
  class: DRevRoute
  options:
    model:    DRev
    type:     object
  requirements:
    sf_method: [get]

drev_devalidation:
  url: /drev/devalidation/:id
  param: { module: drev, action: devalidation }
  class: DRevRoute
  options:
    model:    DRev
    type:     object
  requirements:
    sf_method: [get]

drev_dr:
  url: /drev/dr/:id
  param: { module: drev, action: dr }
  class: DRevRoute
  options:
    model:    DRev
    type:     object
  requirements:
    sf_method: [get, post]

drev_dr_recuperation:
  url: /drev/dr-recuperation/:id
  param: { module: drev, action: drRecuperation }
  class: DRevRoute
  options:
    model:    DRev
    type:     object
  requirements:
    sf_method: [get, post]

drev_dr_import:
  url: /drev/dr-import/:id
  param: { module: drev, action: drImport }
  class: DRevRoute
  options:
    model:    DRev
    type:     object
  requirements:
    sf_method: [get, post]

drev_dr_pdf:
  url: /drev/dr-pdf/:id
  param: { module: drev, action: drPdf }
  class: DRevRoute
  options:
    model:    DRev
    type:     object
  requirements:
    sf_method: [get]

drev_exploitation:
  url: /drev/exploitation/:id
  param: { module: drev, action: exploitation }
  class: DRevRoute
  options:
    model:    DRev
    type:     object
  requirements:
    sf_method: [get, post]

drev_revendication_recapitulatif:
  url: /drev/drev_revendication-recapitulatif/:id
  param: { module: drev, action: revendicationRecapitulatif }
  class: DRevRoute
  options:
    model:    DRev
    type:     object
  requirements:
    sf_method: [get, post]

drev_revendication_ajout:
  url: /drev/revendication/:id/ajout
  param: { module: drev, action: revendicationAjoutProduit }
  class: DRevRoute
  options:
    model:    DRev
    type:     object
  requirements:
    sf_method: [get, post]

drev_revendication_appellation_ajout:
  url: /drev/revendication/:id/appellation_ajout
  param: { module: drev, action: revendicationAjoutAppellation }
  class: DRevRoute
  options:
    model:    DRev
    type:     object
  requirements:
    sf_method: [post]

drev_revendication:
  url: /drev/revendication/:id/:appellation
  param: { module: drev, action: revendication, appellation: 0 }
  class: DRevRoute
  options:
    model:    DRev
    type:     object
  requirements:
    sf_method: [get, post]

drev_revendication_cepage:
  url: /drev/revendication/:id/cepage/:hash
  param: { module: drev, action: revendicationCepage }
  class: DRevNoeudRoute
  options:
    model:    DRevAppellation
    type:     object
  requirements:
    sf_method: [get, post]

drev_revendication_cepage_ajout:
  url: /drev/revendication/:id/cepage/:hash/ajout
  param: { module: drev, action: revendicationCepageAjoutProduit }
  class: DRevNoeudRoute
  options:
    model:    DRevAppellation
    type:     object
  requirements:
    sf_method: [post]

drev_degustation_conseil:
  url: /drev/degustation-conseil/:id
  param: { module: drev, action: degustationConseil }
  class: DRevRoute
  options:
    model:    DRev
    type:     object
  requirements:
    sf_method: [get, post]

drev_lots:
  url: /drev/lots/:id/:prelevement
  param: { module: drev, action: lots }
  class: DRevPrelevementRoute
  options:
    model:    DRevPrelevement
    type:     object
  requirements:
    sf_method: [get, post]

drev_lots_ajout:
  url: /drev/lots/:id/:prelevement/ajout
  param: { module: drev, action: lotsAjoutProduit }
  class: DRevPrelevementRoute
  options:
    model:    DRevPrelevement
    type:     object
  requirements:
    sf_method: [post]

drev_controle_externe:
  url: /drev/controle-externe/:id
  param: { module: drev, action: controleExterne }
  class: DRevRoute
  options:
    model:    DRev
    type:     object
  requirements:
    sf_method: [get, post]

drev_validation:
  url: /drev/validation/:id
  param: { module: drev, action: validation }
  class: DRevRoute
  options:
    model:    DRev
    type:     object
  requirements:
    sf_method: [get, post]

drev_validation_admin:
  url: /drev/validation_admin/:id
  param: { module: drev, action: validationAdmin }
  class: DRevRoute
  options:
    model:    DRev
    type:     object
  requirements:
    sf_method: [get]

drev_confirmation:
  url: /drev/confirmation/:id
  param: { module: drev, action: confirmation }
  class: DRevRoute
  options:
    model:    DRev
    type:     object
  requirements:
    sf_method: [get, post]

drev_visualisation:
  url: /drev/visualisation/:id
  param: { module: drev, action: visualisation }
  class: DRevRoute
  options:
    model:    DRev
    type:     object
  requirements:
    sf_method: [get, post]

drev_export_pdf:
  url: /drev/pdf/:id
  param: { module: drev, action: PDF }
  class: DRevRoute
  options:
    model:    DRev
    type:     object
  requirements:
    sf_method: [get]

#DREVMARC
drevmarc_create:
  url: /drevmarc/creation/:id
  param: { module: drevmarc, action: create }
  class: EtablissementRoute
  options:
    model:    Etablissement
    type:     object
  requirements:
    sf_method: [get]

drevmarc_edit:
  url: /drevmarc/edition/:id
  param: { module: drevmarc, action: edit }
  class: DRevMarcRoute
  options:
    model:    DRevMarc
    type:     object
  requirements:
    sf_method: [get]

drevmarc_exploitation:
  url: /drevmarc/exploitation/:id
  param: { module: drevmarc, action: exploitation }
  class: DRevMarcRoute
  options:
    model:    DRevMarc
    type:     object
  requirements:
    sf_method: [get, post]

drevmarc_revendication:
  url: /drevmarc/revendication/:id
  param: { module: drevmarc, action: revendication }
  class: DRevMarcRoute
  options:
    model:    DRevMarc
    type:     object
  requirements:
    sf_method: [get, post]

drevmarc_validation:
  url: /drevmarc/validation/:id
  param: { module: drevmarc, action: validation }
  class: DRevMarcRoute
  options:
    model:    DRevMarc
    type:     object
  requirements:
    sf_method: [get, post]

drevmarc_validation_admin:
  url: /drevmarc/validation_admin/:id
  param: { module: drevmarc, action: validationAdmin }
  class: DRevMarcRoute
  options:
    model:    DRevMarc
    type:     object
  requirements:
    sf_method: [get]

drevmarc_confirmation:
  url: /drevmarc/confirmation/:id
  param: { module: drevmarc, action: confirmation }
  class: DRevMarcRoute
  options:
    model:    DRevMarc
    type:     object
  requirements:
    sf_method: [get, post]

drevmarc_visualisation:
  url: /drevmarc/visualisation/:id
  param: { module: drevmarc, action: visualisation }
  class: DRevMarcRoute
  options:
    model:    DRevMarc
    type:     object
  requirements:
    sf_method: [get, post]

drevmarc_delete:
  url: /drevmarc/suppression/:id
  param: { module: drevmarc, action: delete }
  class: DRevMarcRoute
  options:
    model:    DRevMarc
    type:     object
  requirements:
    sf_method: [get]

drevmarc_devalidation:
  url: /drevmarc/devalidation/:id
  param: { module: drevmarc, action: devalidation }
  class: DRevMarcRoute
  options:
    model:    DRevMarc
    type:     object
  requirements:
    sf_method: [get]


drevmarc_export_pdf:
  url: /drevmarc/pdf/:id
  param: { module: drevmarc, action: PDF }
  class: DRevMarcRoute
  options:
    model:    DRevMarc
    type:     object
  requirements:
    sf_method: [get]

#Mon compte

compte_creation:
  url: /compte
  param: { module: compte, action: creation }

compte_creation_confirmation:
  url: /compte-creation-confirmation
  param: { module: compte, action: creationConfirmation }

compte_mot_de_passe_oublie:
  url: /mot_de_passe_oublie
  param: { module: compte, action: motDePasseOublie }

mon_compte:
  url: /mon-compte
  param: { module: compte, action: modification }

redirect_to_mon_compte_civa:    
  url: /mon-compte-civa
  param: { module: compte, action: redirectToMonCompteCiva }

#Compte et etablissement admin
compte_creation_admin:
  url: /compte-admin-creation
  param: { module: compte, action: creationAdmin }
  
compte_visualisation_admin:
  url: /compte-visualisation/:id
  param: { module: compte, action: visualisationAdmin }  
  class: CompteRoute
  options:
    model:    Compte
    type:     object
  requirements:
    sf_method: [get]
    
compte_modification_admin:
  url: /compte-modification/:id
  param: { module: compte, action: modificationAdmin }  
  class: CompteRoute
  options:
    model:    Compte
    type:     object
  requirements:
    sf_method: [get,post]

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
