# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules

drev_create:
  url: /drev/creation
  param: { module: drev, action: create }

drev_edit:
  url: /drev/edition/:id
  param: { module: drev, action: edit }
  class: DRevRoute
  options:
    model:    DRev
    type:     object
  requirements:
    sf_method: [get]

drev_revendication:
  url: /drev/revendication/:id
  param: { module: drev, action: revendication }
  class: DRevRoute
  options:
    model:    DRev
    type:     object
  requirements:
    sf_method: [get, post]

drev_degustation_conseil:
  url: /drev/degustation-conseil/:id
  param: { module: drev, action: degustationConseil }
  class: DRevRoute
  options:
    model:    DRev
    type:     object
  requirements:
    sf_method: [get, post]

drev_lots:
  url: /drev/lots/:id/:prelevement
  param: { module: drev, action: lots }
  class: DRevPrelevementRoute
  options:
    model:    DRevPrelevement
    type:     object
  requirements:
    sf_method: [get, post]

drev_lots_ajout:
  url: /drev/lots/:id/:prelevement/ajout
  param: { module: drev, action: lotsAjoutProduit }
  class: DRevPrelevementRoute
  options:
    model:    DRevPrelevement
    type:     object
  requirements:
    sf_method: [post]

drev_controle_externe:
  url: /drev/controle-externe/:id
  param: { module: drev, action: controleExterne }
  class: DRevRoute
  options:
    model:    DRev
    type:     object
  requirements:
    sf_method: [get, post]

drev_validation:
  url: /drev/validation/:id
  param: { module: drev, action: validation }
  class: DRevRoute
  options:
    model:    DRev
    type:     object
  requirements:
    sf_method: [get, post]

drev_export_pdf:
  url: /drev/pdf/:id
  param: { module: drev, action: PDF }
  class: DRevRoute
  options:
    model:    DRev
    type:     object
  requirements:
    sf_method: [get]

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
