# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html
    X-UA-Compatible: IE=edge

  metas:
    title:         "Plateforme de télédéclaration de l'AVA"
    charset:       "utf-8"
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow
    viewport:      "width=device-width, initial-scale=1"

  stylesheets:    [lib/bootstrap/bootstrap.min.css, main.css]

  javascripts:    [lib/jquery/jquery-ui.min.js, lib/bootstrap/bootstrap.min.js, lib/autocomplete.js]

  has_layout:     true
  layout:         layout
