# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  organisme:
    nom: "Syndicat Général des Vignerons Réunis des Côtes du Rhône"
  elasticversion: '2.4.6'
  parcellaire_irrigable:
    ressources: ["Forage", "Etang", "Retenue collinaire","Réseau urbain"]
    materiels: ["Goutte à goutte", "Canon", "Système enterré"]
  float:
    default_decimal_format: 2
    max_decimal_authorized: 4
  communes:
    denominations:
      DEFAUT : [84088]
