all:
  configuration:
    parcellaire:
      ecart_rangs_max: 25000
      ecart_pieds_max: 25000
      ecart_pieds_min:  8000
      manquant:
        pc_min: 20
      affectation:
        needs_intention: false
      aires:
        Ventoux:
          name: "Ventoux"
          color: "#ab3f97"
          denomination_id: "01363"
