all:
  configuration:
    drev:
      mentions_complementaire: true
      import_with_mentions_complementaire: true
      validation_odg: 'auto'
      etape_superficie: false
      dr_douane_required: false
      degustation: true
      specificite_lot: true
      engagement_pdf: true
      send_email_operateur: false
      email_disabled: true
      volume_seuil:
        hash: certifications/IGP/genres/TRANQ/appellations/MED/mentions/DEFAUT/lieux/DEFAUT/couleurs/rose/cepages/DEFAUT
        campagne: 2022-2023